apiVersion: v1
kind: Service
metadata:
  name: mongoexp-service
spec:
  selector:
    app: mongoexp
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 30004



