apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp-deploy
  labels:
    app: mongoexp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexp
  template:
    metadata:
      labels:
        app: mongoexp
    spec:
      containers:
      - name: mongoexp
        image: mongo-express:latest
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: databaseurl
              

